# Site settings
title: EXPERIENTIA DOCET
description: > # this means to ignore newlines until "baseurl:"
  hanjack
baseurl:  # the subpath of your site, e.g. /blog/
url: # the base hostname & protocol for your site
email: haanjack@gmail.com
facebook_username: haanjack
twitter_username: haanjack
github_username:  haanjack
gplus_username:  haanjack
disqus_username: haanjack

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
plugins: ['jekyll-paginate', 'jekyll-mermaid']
paginate: 15
paginate_path: "/blog/page:num/"
mermaid:
  src: '/scripts/mermaid.js'


collections:
   gpu:
     output: true
     permalink: /gpu/:path/
  # metal:
  #  output: true
  #  permalink: /metal/:path/
  # portfolio:
  #   output: false
  #   permalink: /portfolio/:path/
  #poetry:
  #    output: true
  #    permalink: /poetry/:path/
