# Site settings
title: hanjack
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
email: haanjack@gmail.com
twitter_username: haanjack
github_username:  haanjack
gplus_username:  haanjack
disqus_username: haanjack

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
gems: ['jekyll-paginate', 'jekyll-mermaid']
paginate: 15
paginate_path: "/blog/page:num/"
mermaid:
  src: '/scripts/mermaid.js'


collections:
  cuda:
    output: true
    permalink: /cuda/:path/
  metal:
    output: true
    permalink: /metal/:path/
  portfolio:
    output: true
    permalink: /portfolio/:path/
#poetry:
#    output: true
#    permalink: /poetry/:path/